/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package icecream;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trust
 */
	
public class ice extends javax.swing.JFrame implements MouseListener {

    /**
     * Creates new form ice
     */
    public ice() {
        initComponents();
        lcho.addMouseListener(this);
        lman.addMouseListener(this);
        llem.addMouseListener(this);
        lvan.addMouseListener(this);
        lstw.addMouseListener(this);
        lbtr.addMouseListener(this);
        lbfs.addMouseListener(this);
        laj.addMouseListener(this);
        lgj.addMouseListener(this);
        lmj.addMouseListener(this);
        loj.addMouseListener(this);
        lsfj.addMouseListener(this);
        llmd.addMouseListener(this);
        lmoc.addMouseListener(this);
        lbt.addMouseListener(this);
        lrt.addMouseListener(this);
        lbc.addMouseListener(this);
        lrc.addMouseListener(this);
        lshk.addMouseListener(this);
        lcoc.addMouseListener(this);
        lwat.addMouseListener(this);
        
       
   
    }

   DefaultTableModel model =  new DefaultTableModel();
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lman = new javax.swing.JLabel();
        lcho = new javax.swing.JLabel();
        lvan = new javax.swing.JLabel();
        llem = new javax.swing.JLabel();
        lstw = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbtr = new javax.swing.JLabel();
        lbfs = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        laj = new javax.swing.JLabel();
        lgj = new javax.swing.JLabel();
        lmj = new javax.swing.JLabel();
        loj = new javax.swing.JLabel();
        lsfj = new javax.swing.JLabel();
        llmd = new javax.swing.JLabel();
        lcho7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lmoc = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbt = new javax.swing.JLabel();
        lbc = new javax.swing.JLabel();
        lrt = new javax.swing.JLabel();
        lshk = new javax.swing.JLabel();
        lcoc = new javax.swing.JLabel();
        lwat = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lrc = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        txtsub = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtpay = new javax.swing.JTextField();
        txtbal = new javax.swing.JTextField();
        jtaka = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jLabel1.setFont(new java.awt.Font("Sitka Small", 3, 36)); // NOI18N
        jLabel1.setText("UAP ICE CREAM SHOP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(333, 333, 333))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
        );

        lman.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\MAN.jpg")); // NOI18N
        lman.setText("jLabel2");

        lcho.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\CHOCO.jpg")); // NOI18N
        lcho.setText("jLabel2");

        lvan.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\VAN.jpg")); // NOI18N
        lvan.setText("jLabel2");

        llem.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\LEM.jpg")); // NOI18N
        llem.setText("jLabel2");

        lstw.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\STRAW.jpg")); // NOI18N
        lstw.setText("jLabel2");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("CHOCOLATE");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setText("MANGO");

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setText("LEMON");

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel13.setText("VANILLA");

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel14.setText("STRAWBERRY");

        lbtr.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\BS.jpg")); // NOI18N
        lbtr.setText("jLabel2");

        lbfs.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\BF.jpg")); // NOI18N
        lbfs.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("BUTTERSCOTCH");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("BLACK FOREST");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lcho, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lman, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(llem, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lvan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lstw, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbtr, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel11)
                        .addGap(156, 156, 156)
                        .addComponent(jLabel12)
                        .addGap(129, 129, 129)
                        .addComponent(jLabel13)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel14)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbfs, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(52, 52, 52))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lman, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcho, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(llem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lstw, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtr, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbfs, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("ICE CREAM", jPanel2);

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel15.setText("APPLE JUICE");

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel16.setText("GRAPE JUICE");

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel17.setText("MANGO JUICE");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("ORANGE JUICE");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("SEASONAL FRUIT JUICE");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("MOCKTAIL");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("COCA COLA");

        laj.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\AJ.jpg")); // NOI18N
        laj.setText("jLabel2");

        lgj.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\GJ.jpg")); // NOI18N
        lgj.setText("jLabel2");

        lmj.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\MJ.jpg")); // NOI18N
        lmj.setText("jLabel2");

        loj.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\OJ.jpg")); // NOI18N
        loj.setText("jLabel2");

        lsfj.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\SFJ.jpg")); // NOI18N
        lsfj.setText("jLabel2");

        llmd.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\LEMONADE.jpg")); // NOI18N
        llmd.setText("jLabel2");

        lcho7.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_1\\images\\MOCKTAIL.jpg")); // NOI18N
        lcho7.setText("jLabel2");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("LEMONADE");

        lmoc.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\MOCKTAIL.jpg")); // NOI18N
        lmoc.setText("jLabel2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel15)
                        .addGap(117, 117, 117)
                        .addComponent(jLabel16)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel17)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel4)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel6)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel19)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel7)
                        .addGap(164, 164, 164)
                        .addComponent(jLabel8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(laj, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lgj, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lmj, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loj, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lsfj, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(llmd, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lmoc, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217)
                        .addComponent(lcho7, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laj, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lgj, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lmj, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loj, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lsfj, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(llmd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcho7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lmoc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel8))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel19)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("JUICE", jPanel5);

        lbt.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\BTEA.jpg")); // NOI18N
        lbt.setText("jLabel2");

        lbc.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\BCOF.jpg")); // NOI18N
        lbc.setText("jLabel2");

        lrt.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\TEA.jpg")); // NOI18N
        lrt.setText("jLabel2");

        lshk.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\SHAKE.jpg")); // NOI18N
        lshk.setText("jLabel2");

        lcoc.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\COCA COLA.jpg")); // NOI18N
        lcoc.setText("jLabel2");

        lwat.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\WAT.jpg")); // NOI18N
        lwat.setText("jLabel2");

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel21.setText("BLACK TEA");

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel22.setText("REGULAR TEA");

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel23.setText("BLACK COFFEE");

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel24.setText("REGULAR COFFEE");

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel25.setText("SHAKE");

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        lrc.setIcon(new javax.swing.ImageIcon("C:\\Users\\trust\\Documents\\NetBeansProjects\\icecreamshop_project\\images\\COF.jpg")); // NOI18N
        lrc.setText("jLabel2");

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel26.setText("COCA COLA");

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel28.setText("MINERAL WATER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lrt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbc, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lrc, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lshk, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lcoc, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lwat, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(94, 94, 94)
                .addComponent(jLabel22)
                .addGap(113, 113, 113)
                .addComponent(jLabel23)
                .addGap(91, 91, 91)
                .addComponent(jLabel24)
                .addGap(104, 104, 104)
                .addComponent(jLabel25)
                .addGap(140, 140, 140)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(41, 41, 41))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(782, Short.MAX_VALUE)
                    .addComponent(jLabel27)
                    .addGap(580, 580, 580)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lrt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lshk, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcoc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lwat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lrc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(163, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(43, 43, 43)))
        );

        jTabbedPane1.addTab("BEVARAGE", jPanel3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Total Amount (Tk.)");

        txtsub.setBackground(new java.awt.Color(255, 204, 204));
        txtsub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Payment (Tk.)");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Balance (Tk.)");

        txtpay.setBackground(new java.awt.Color(204, 255, 255));
        txtpay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpayActionPerformed(evt);
            }
        });

        txtbal.setBackground(new java.awt.Color(204, 204, 255));
        txtbal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtbal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbalActionPerformed(evt);
            }
        });

        jtaka.setBackground(new java.awt.Color(255, 204, 255));
        jtaka.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtaka.setText("PAY");
        jtaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtsub, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jtaka, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtaka, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtbal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubActionPerformed

    private void txtpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpayActionPerformed

    private void jtakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtakaActionPerformed
        // TODO add your handling code here:
        String a=txtsub.getText();
        String b=txtpay.getText();
        int c=Integer.parseInt(a);
        int d=Integer.parseInt(b);
        txtbal.setText(Integer.toString(d-c));
    }//GEN-LAST:event_jtakaActionPerformed

    private void txtbalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ice().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton jtaka;
    private javax.swing.JLabel laj;
    private javax.swing.JLabel lbc;
    private javax.swing.JLabel lbfs;
    private javax.swing.JLabel lbt;
    private javax.swing.JLabel lbtr;
    private javax.swing.JLabel lcho;
    private javax.swing.JLabel lcho7;
    private javax.swing.JLabel lcoc;
    private javax.swing.JLabel lgj;
    private javax.swing.JLabel llem;
    private javax.swing.JLabel llmd;
    private javax.swing.JLabel lman;
    private javax.swing.JLabel lmj;
    private javax.swing.JLabel lmoc;
    private javax.swing.JLabel loj;
    private javax.swing.JLabel lrc;
    private javax.swing.JLabel lrt;
    private javax.swing.JLabel lsfj;
    private javax.swing.JLabel lshk;
    private javax.swing.JLabel lstw;
    private javax.swing.JLabel lvan;
    private javax.swing.JLabel lwat;
    private javax.swing.JTextField txtbal;
    private javax.swing.JTextField txtpay;
    private javax.swing.JTextField txtsub;
    // End of variables declaration//GEN-END:variables

  
@Override
public void mouseClicked(MouseEvent e) {
 
if(e.getSource() == lcho )
{
String name = "Chocolate Ice Cream";
int price = 250;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
else if(e.getSource() == lman )
{
String name = "Mango Ice Cream";
int price = 150;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
 
else if(e.getSource() == llem )
{
String name = "Lemon Ice Cream";
int price = 120;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
else if(e.getSource() == lvan )
{
String name = "Vanilla Ice Cream";
int price = 220;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
else if(e.getSource() == lstw )
{
String name = "Strawberry Ice Cream";
int price = 250;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
else if(e.getSource() == lbtr )
{
String name = "Butterscotch Ice Cream";
int price = 350;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
else if(e.getSource() == lbfs )
{
String name = "Black Forest Ice Cream";
int price = 350;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}




 
if(e.getSource() == laj )
{
String name = "Apple Juice";
int price = 220;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
 
else if(e.getSource() == lgj )
{
String name = "Grape Juice";
int price = 250;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
 
 
else if(e.getSource() == lmj )
{
String name = "Mango Juice";
int price = 125;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
else if(e.getSource() == loj )
{
String name = "Orange Juice";
int price = 125;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
else if(e.getSource() == lsfj )
{
String name = "Seasonal Fruit Juice";
int price = 150;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
else if(e.getSource() == llmd )
{
String name = "Lemonade";
int price = 100;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
else if(e.getSource() == lmoc )
{
String name = "Mocktail";
int price = 145;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}





if(e.getSource() == lbt )
{
String name = "Black Tea";
int price = 40;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
 
else if(e.getSource() == lrt )
{
String name = "Regular Tea";
int price = 50;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
 
 
else if(e.getSource() == lbc )
{
String name = "Black Coffee";
int price = 75;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
else if(e.getSource() == lrc )
{
String name = "Regular Coffee";
int price = 90;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
else if(e.getSource() == lshk )
{
String name = "Shake";
int price = 125;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
else if(e.getSource() == lcoc )
{
String name = "Coca Cola";
int price = 35;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
else if(e.getSource() == lwat )
{
String name = "Water";
int price = 15;
 
int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter The Qty"));
int tot = price * qty;
 
model = (DefaultTableModel)jTable4.getModel();
 
model.addRow(new Object[]
{
name,
price,
qty,
tot,
});
 
int sum = 0;
 
for(int i = 0; i <jTable4.getRowCount(); i++)
{
 
sum = sum + Integer.parseInt(jTable4.getValueAt(i, 3).toString());
 
}
txtsub.setText(Integer.toString(sum));
}
}
 
@Override
public void mousePressed(MouseEvent e) {
 
}
 
@Override
public void mouseReleased(MouseEvent e) {
 
}
 
@Override
public void mouseEntered(MouseEvent e) {
 
}
 
@Override
public void mouseExited(MouseEvent e) {
 
}
}